creation_rules:
  # Kubernetes secrets (*.sops.yaml files)
  - path_regex: \.sops\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # Replace with your age public key from: age-keygen -o .age-key.txt

  # Ansible vault files
  - path_regex: ansible/inventory/group_vars/.*/vault\.yml$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
